"use client";

import "./css/style.css";

import { animated, config, to, useSpring } from "@react-spring/web";

import Banner from "@/components/banner";
import Header from "@/components/ui/header";
import { Inter } from "next/font/google";
import styles from "./solarblog/styles.module.css";
import { usePathname } from "next/navigation";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export async function getServerSideProps(context: any) {
//   const currentUrl = context.url;
//   return {
//     props: { currentUrl },
//   };
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let currentRouter = usePathname();
  console.log(currentRouter);
  console.log(currentRouter, "children");
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          {currentRouter !== "" ? <></> : <Header />}
          {children}
          {currentRouter !== "" ? <></> : <Banner />}
        </div>
      </body>
    </html>
  );
}
