import styles from './../../styles/PageMd.module.css'
import pluginGfm from '@bytemd/plugin-gfm'
import { Editor, Viewer } from '@bytemd/react'
// todo:plugins
import breaks from '@bytemd/plugin-breaks'
import frontmatter from '@bytemd/plugin-frontmatter'
import gemoji from '@bytemd/plugin-gemoji'
import highlight from '@bytemd/plugin-highlight'
import math from '@bytemd/plugin-math'
import mediumZoom from '@bytemd/plugin-medium-zoom'
import mermaid from '@bytemd/plugin-mermaid'

import type { NextPage } from 'next'
import Head from 'next/head'
import { useMemo, useState } from 'react'
// import { useSetState } from 'ahooks'
import 'bytemd/dist/index.css'
type modeType = 'split' | 'auto' | 'tab'
const PageMd: NextPage = () => {
  const [value, setValue] = useState('')
  const [mode, setMode] = useState('split' as modeType)
  const plugins = useMemo(() => [
    pluginGfm(),
    frontmatter(), breaks(), gemoji(), highlight(), math(), mediumZoom(), mermaid()], [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Viewer value="abc" /> */}

      <Editor
        mode={mode}
        value={value}
        plugins={plugins}
        uploadImages={async (files) => {
          // upload images here
          return [
            {
              url: 'https://picsum.photos/200/300',
            },
          ]
        }}
        onChange={(v) => {
          setValue(v)
        }}
      />
    </div>
  )
}

export default PageMd